program: cli_hpo_srvm_high_frequency_v2.py
method: random
metric:
  name: val_r2c_G
  goal: maximize
parameters:
  batch_size:
    values: [1]
  epochs:
    values: [30, 50, 70]
  learning_rate:
    values: [0.01, 0.005, 0.001]
  l2_reg:
    values: [1e-6, 1e-5, 1e-4, 1e-3, 1e-2]
  num_hidden_layers:
    values: [1, 2, 3]
  num_hidden_units:
    values: [10, 20, 30]
  max_linear_prices_multiplier:
    values: [60] #NOTE: this is for the random price vector generation, used to be 3 in all domains other than MRVM, where it is 5 for the national bidder and 50 for the other 2
  price_file_name:
    values: ["values_for_null_price_seeds1-100"]
  use_gradient_clipping:
    values: [False]
  dropout_prob:
    values: [0.0]
  lin_skip_connection:
    values: [True, False]
  scale_multiplier: 
    values: [1]  #NOTE: [1, 1.5, 2, 4] for MRVM, only affects dynamic scaling. 
command:
  - ${interpreter}
  - ${program}
  - ${args}